# Generated by Django 4.2.30 on 2026-07-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist_name',
            field=models.CharField(default='Primary Wishlist', max_length=100),
        ),
    ]
