# Generated by Django 4.2.30 on 2026-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_add_rating_and_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
